server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: /home/pedro/git/alura/spring-cloud-microservices/microservices-repo