spring:
  data:
    mongodb:
      uri: mongodb+srv://pedro-spring-cloud-alura:cg8re5%40%2712%273450kiSBFte6C@spring-cluster-vglus.mongodb.net/test?retryWrites=true&w=majority&maxIdleTimeMS=60000&maxPoolSize=10&connectTimeoutMS=60000&socketTimeoutMS=60000
      database: fornecedorDB
